### ISSUE TITLE
White-list of exeptions on transaction

### ISSUE THREAD

**Issue by JGGrande** [Yamanlk/transactional-core#1]
Hello, I would like to make a suggestion for the next versions, to allow a white-list of exeptions, in some cases we need to use exeptions to trigger http responses, such as when using express-async-errors, so exeptions from business rules would not get in the way the course of the transection and will allow for better customized error messages.

**Comment by Yamanlk** [comment]
Hi, I didn't understand the use case, you are saying that functions running inside the transaction might throw some errors, but these errors should not cause the transaction to rollback ?
